name: Miatoll Port-Mation
run-name: ${{ github.event.inputs.build_name }}

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Input Job Name'
        required: true
        default: 'Miatoll Port-Mation'
      ota_url:
        description: 'OTA full zip URL'
        required: true
      build_selection:
        description: 'Select The Script To Build'
        required: true
        type: choice
        options:
          - miatoll_hyper_cn
          - miatoll_hyper_global
          - miatoll_oplus_cn
          - miatoll_oplus_global

jobs:
  build:
    name: ${{ github.event.inputs.build_name }}
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Dhaka #(Bangladesh TimeZone)

    steps:
      - name: Checkout this repo (public)
        uses: actions/checkout@v4

      - name: Remove public repo files (optional)
        run: rm -rf * .??*

      - name: Clone XdOps Repo
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/iput-object/XdOps.git temp_xdops

      - name: Move files from XdOps to root
        run: |
          shopt -s dotglob
          mv temp_xdops/* .
          rm -rf temp_xdops

      - name: Make rom-scripts executable
        run: |
          chmod +x rom-scripts/*.sh

      - name: Run ROM build script
        run: |
          ./rom-scripts/${{ github.event.inputs.build_selection }}.sh "${{ github.event.inputs.ota_url }}"
